---

name:
    genkouyoushi-generator
version:
    0.1.0.0
synopsis:
    Generate Genkouyoushi Paper for Japanese Writing Practice
# description:
homepage:
    https://github.com/prikhi/genkouyoushi-generator#readme
github:
    prikhi/genkouyoushi-generator
license:
    GPL-3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2019 Pavan Rikhi
category:
    Graphics
extra-source-files:
    - README.md

dependencies:
    - base >= 4.7 && < 5
    - diagrams-lib

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

library:
    source-dirs: src
    dependencies:
        - colour
        - mtl
        - scientific
        - text

executables:
    genkouyoushi-gen:
        main:
            Main.hs
        source-dirs:
            cli
        dependencies:
            - genkouyoushi-generator
            - cmdargs
            - diagrams-rasterific
    genkouyoushi-api:
        main:
            Main.hs
        source-dirs:
            api
        dependencies:
            - genkouyoushi-generator
            - aeson
            - bytestring
            - diagrams-rasterific
            - servant-server
            - wai
            - wai-extra
            - warp
